### ISSUE TITLE
On update: clicking on update button causes strange failed GET

### ISSUE THREAD

**Issue by angmas** [femme-squad-plus-one/all-the-things-client#22]
I noticed that in the console, sometimes when I click on the update button, the console displays a failed GET request with a successful GET request.

It almost looks like the GET processes twice.
<img width="632" alt="screen shot 2017-05-18 at 3 39 56 pm" src="https://cloud.githubusercontent.com/assets/26231241/26220360/4e57d7be-3be0-11e7-9b34-cac2cb1c3277.png">

**Comment by aeabbott** [comment]
Resolved by Nari. Removed click handler from the pencil icon.
